name: Publish

on:
  workflow_dispatch:

jobs:
  publish-npm:
    name: Publish npm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          cache: npm

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Jupyter lite
        run: pip install -r requirements.txt

      - name: Install node modules
        run: npm ci

      - name: Build static files
        run: |
          npm run build

      - name: Publish to npm and commit tags back to main
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          npm run release
          git push --follow-tags origin main
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
